# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('artist', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField(null=True)),
                ('composer', models.CharField(max_length=200, null=True)),
                ('track', models.IntegerField(null=True)),
                ('album', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DAGR',
            fields=[
                ('GUID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('size', models.BigIntegerField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('annotated_name', models.CharField(max_length=200)),
                ('SHA1', models.CharField(blank=True, max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('local_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='DAGR.DAGR')),
                ('parent_GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(max_length=16)),
                ('tweet_type', models.CharField(choices=[('T', 'Tweet'), ('R', 'Reply'), ('RT', 'Retweet')], max_length=2)),
                ('likes', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_width', models.IntegerField()),
                ('video_height', models.IntegerField()),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
        migrations.CreateModel(
            name='Word_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('paragraph_count', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField()),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='GUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAGR.DAGR'),
        ),
    ]
