# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAGR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word_document',
            old_name='page_count',
            new_name='char_count',
        ),
        migrations.RemoveField(
            model_name='word_document',
            name='paragraph_count',
        ),
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dagr',
            name='datatype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word_document',
            name='date_created',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word_document',
            name='date_modified',
            field=models.CharField(max_length=200),
        ),
    ]
