# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAGR', '0002_auto_20170510_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dagr',
            name='SHA1',
        ),
    ]
