# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DAGR', '0003_remove_dagr_sha1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='artist',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='year',
        ),
    ]
